# Generated by Django 5.1.3 on 2024-11-25 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio web')),
                ('ubicacion', models.CharField(max_length=100, verbose_name='Ubicación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.TextField(blank=True, max_length=500, verbose_name='Biografía')),
                ('profesion', models.CharField(blank=True, max_length=100, verbose_name='Profesión')),
                ('habilidades', models.TextField(blank=True, verbose_name='Habilidades')),
                ('ubicacion', models.CharField(blank=True, max_length=100, verbose_name='Ubicación')),
                ('modalidad_preferida', models.CharField(blank=True, choices=[('REMOTO', 'Remoto'), ('HIBRIDO', 'Híbrido'), ('PRESENCIAL', 'Presencial')], max_length=10, verbose_name='Modalidad de trabajo preferida')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TITULO', 'Título Profesional'), ('CERTIFICACION', 'Certificación'), ('CURSO', 'Curso'), ('OTRO', 'Otro')], max_length=15, verbose_name='Tipo de documento')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('institucion', models.CharField(max_length=200, verbose_name='Institución')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de emisión')),
                ('archivo', models.FileField(upload_to='documentos/', verbose_name='Archivo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='ProNetix_app.perfil')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='PublicacionTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NORMAL', 'Publicación Normal'), ('TRABAJO', 'Oferta de Trabajo')], default='NORMAL', max_length=10, verbose_name='Tipo de publicación')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del puesto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='publicaciones/', verbose_name='Imagen')),
                ('requisitos', models.TextField(blank=True, null=True, verbose_name='Requisitos')),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación')),
                ('modalidad', models.CharField(blank=True, choices=[('REMOTO', 'Remoto'), ('HIBRIDO', 'Híbrido'), ('PRESENCIAL', 'Presencial')], max_length=10, null=True, verbose_name='Modalidad de trabajo')),
                ('experiencia_requerida', models.CharField(blank=True, choices=[('JUNIOR', 'Junior (0-2 años)'), ('SEMI_SENIOR', 'Semi-Senior (2-4 años)'), ('SENIOR', 'Senior (4+ años)'), ('EXPERTO', 'Experto (8+ años)')], max_length=15, null=True, verbose_name='Experiencia requerida')),
                ('rango_salarial', models.CharField(blank=True, choices=[('1000000-2000000', '$1.000.000 - $2.000.000'), ('2000000-3000000', '$2.000.000 - $3.000.000'), ('3000000-4000000', '$3.000.000 - $4.000.000'), ('4000000-5000000', '$4.000.000 - $5.000.000'), ('5000000-7000000', '$5.000.000 - $7.000.000'), ('7000000-9000000', '$7.000.000 - $9.000.000'), ('9000000_PLUS', 'Más de $9.000.000'), ('POR_ACORDAR', 'Por acordar')], max_length=20, null=True, verbose_name='Rango Salarial')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='ProNetix_app.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REVISADO', 'Revisado'), ('ENTREVISTA', 'En proceso de entrevista'), ('RECHAZADO', 'Rechazado'), ('ACEPTADO', 'Aceptado')], default='PENDIENTE', max_length=20)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='ProNetix_app.publicaciontrabajo')),
            ],
            options={
                'ordering': ['-fecha_postulacion'],
            },
        ),
        migrations.AddIndex(
            model_name='publicaciontrabajo',
            index=models.Index(fields=['tipo'], name='ProNetix_ap_tipo_b7c36c_idx'),
        ),
        migrations.AddIndex(
            model_name='publicaciontrabajo',
            index=models.Index(fields=['activa'], name='ProNetix_ap_activa_134ca8_idx'),
        ),
        migrations.AddIndex(
            model_name='publicaciontrabajo',
            index=models.Index(fields=['autor'], name='ProNetix_ap_autor_i_e0d0c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postulacion',
            unique_together={('usuario', 'publicacion')},
        ),
    ]
